spring:
  application:
    name: eureka-consumer

server:
  port: 10233


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10211/eureka/
  instance:
    prefer-ip-address: true


